  package com.company;

  import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import org.graphwalker.core.machine.ExecutionContext;
import org.graphwalker.java.annotation.GraphWalker;
import org.openqa.selenium.Keys;
import org.openqa.selenium.remote.DesiredCapabilities;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

  /**
 * See: http://graphwalker.org/docs/maven_archetype for more details
 * <p/>
 * Implements the GraphWalker model: src/main/resources/SmallTest.graphml
 * The SmallTest.graphml can be opened and edited using http://www.yworks.com/en/products/yfiles/yed/
 * <p/>
 * For convienicene, a jpg image exists side-by-side in the same folder.
 * <p/>
 * The @GraphWalker annotation, has the following meaning:
 * 1) value defines the generator of this test. Please read more
 * on the subject at: http://graphwalker.org/docs/path_generators_and_stop_conditions
 * 2) start defines the first element in the model to be executed. (Element is
 * either a vertex or an edge)
 * <p/>
 * The interface SmallTest, that LoginTest implements, is generated by
 * running: mvn graphwalker:generate-sources
 * also: mvn graphwalker:test
 */
@GraphWalker
public class LoginTest extends  ExecutionContext implements LoginSearchApp {
      AppiumDriver<?> driver;
      DesiredCapabilities capabilities = new DesiredCapabilities();

      @Override
      public void e_OpenApp() {
          String apkpath = "/Users/manue/testAutomation_GraphWalker_MasterThesis_Appium/src/main/resources/apkandroid2.apk";
          File app = new File(apkpath);

          capabilities.setCapability("deviceName", "Nexus 5 API 27");
          capabilities.setCapability("PlatformVersion", "8.1.0");
          capabilities.setCapability("PlatformName", "Android");
          capabilities.setCapability("app", app.getAbsolutePath());
          capabilities.setCapability("appiumVersion", "1.8.0");
          capabilities.setCapability("AutomationName","Appium");
          capabilities.setCapability("fullReset","true");


          try {
              driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

          } catch (MalformedURLException e) {
              e.printStackTrace();
          }


          System.out.println("A app foi iniciada com sucesso.");


      }

      @Override
      public void e_invalidCredentials() {

      }

      @Override
      public void v_SearchResult() {

      }

      @Override
      public void v_LoginPrompted() {

      }

      @Override
      public void e_Exit() {
          driver.resetApp();
          driver.quit();
          System.out.println("Passei pelo exit!");

      }


      @Override
      public void v_AppOpened() {

          System.out.println("A APP está agora aberta!");
      }

      @Override
      public void e_selectEmailProvider() {
          driver.manage().timeouts().implicitlyWait(15,TimeUnit.SECONDS);

          MobileElement el1 = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout[1]/android.widget.ListView/android.widget.TextView");
          el1.click();


  }
  @Override
  public void v_EmailOpened() {

  }

  @Override
  public void v_AppNotStarted() {

      System.out.println("A app ainda não foi inicializada!");
  }

  @Override
  public void e_searchEmail() {

      MobileElement el1 = (MobileElement) driver.findElementByAccessibilityId("Pesquisar");
      el1.click();

      MobileElement el2 = (MobileElement) driver.findElementById("ru.mail.mailapp:id/search_text");
      el2.sendKeys("bem vindo"+"\n");

  }

  @Override
  public void v_LoginMade() {

  }

  @Override
  public void e_validCredentials() {
      MobileElement e12 = (MobileElement) driver.findElementById("ru.mail.mailapp:id/login");
      e12.sendKeys("testesgraphwalker@sapo.pt");

      MobileElement e13 = (MobileElement) driver.findElementById("ru.mail.mailapp:id/password");
      e13.sendKeys("Testesgraphwalker!199");


      MobileElement e14 = (MobileElement) driver.findElementById("ru.mail.mailapp:id/sign_in");
      e14.click();


  }

  @Override
  public void e_CloseApp() {
     driver.resetApp();
     driver.quit();
     System.out.println("Fechei a APP!");

  }


    @Override
  public void e_logout() {

        MobileElement el1 = (MobileElement) driver.findElementByAccessibilityId("Navegar para cima");
        el1.click();

        MobileElement el2 = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/ru.mail.fragments.view.drawer.DrawerLayout/android.widget.RelativeLayout[2]/android.widget.LinearLayout/android.widget.ListView/android.widget.LinearLayout[10]/android.widget.RelativeLayout/android.widget.TextView");
        el2.click();

        MobileElement el3 = (MobileElement) driver.findElementById("android:id/button1");
        el3.click();

      System.out.println("Fiz logout na APP!");

  }


  @Override
  public void e_Init() {
      System.out.println("Iniciou a execução.");

  }

  @Override
  public void e_ClickToOpen() {
      MobileElement el9 = (MobileElement) driver.findElementById("ru.mail.mailapp:id/sender");
      el9.click();
  }

      @Override
      public void e_giveAccessApp() {
          MobileElement el5 = (MobileElement) driver.findElementById("ru.mail.mailapp:id/button_skip");
          el5.click();

          MobileElement el6 = (MobileElement) driver.findElementById("ru.mail.mailapp:id/button_skip");
          el6.click();

          MobileElement el7 = (MobileElement) driver.findElementById("ru.mail.mailapp:id/welcome_done");
          el7.click();



      }

      @Override
      public void v_appAccessGiven() {

          driver.manage().timeouts().implicitlyWait(5,TimeUnit.SECONDS);
          MobileElement e20 = (MobileElement) driver.findElementById("ru.mail.mailapp:id/mail_fragment_frame");
          e20.click();
          driver.manage().timeouts().implicitlyWait(2,TimeUnit.SECONDS);

      }

  }

